// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAthlete = `-- name: CreateAthlete :execresult
INSERT INTO athletes (name, grade, personal_record, events) VALUES (?, ?, ?, ?)
`

type CreateAthleteParams struct {
	Name           string
	Grade          int32
	PersonalRecord string
	Events         string
}

func (q *Queries) CreateAthlete(ctx context.Context, arg CreateAthleteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAthlete,
		arg.Name,
		arg.Grade,
		arg.PersonalRecord,
		arg.Events,
	)
}

const createMeet = `-- name: CreateMeet :execresult
INSERT INTO meets (name, date, location, description) VALUES (?, ?, ?, ?)
`

type CreateMeetParams struct {
	Name        string
	Date        time.Time
	Location    string
	Description string
}

func (q *Queries) CreateMeet(ctx context.Context, arg CreateMeetParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMeet,
		arg.Name,
		arg.Date,
		arg.Location,
		arg.Description,
	)
}

const createResult = `-- name: CreateResult :execresult
INSERT INTO results (athlete_id, meet_id, event, time, place) VALUES (?, ?, ?, ?, ?)
`

type CreateResultParams struct {
	AthleteID int32
	MeetID    int32
	Event     string
	Time      string
	Place     int32
}

func (q *Queries) CreateResult(ctx context.Context, arg CreateResultParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createResult,
		arg.AthleteID,
		arg.MeetID,
		arg.Event,
		arg.Time,
		arg.Place,
	)
}

const deleteAthlete = `-- name: DeleteAthlete :exec
DELETE FROM athletes WHERE id = ?
`

func (q *Queries) DeleteAthlete(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAthlete, id)
	return err
}

const deleteMeet = `-- name: DeleteMeet :exec
DELETE FROM meets WHERE id = ?
`

func (q *Queries) DeleteMeet(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMeet, id)
	return err
}

const deleteResult = `-- name: DeleteResult :exec
DELETE FROM results WHERE id = ?
`

func (q *Queries) DeleteResult(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteResult, id)
	return err
}

const getAllAthletes = `-- name: GetAllAthletes :many
SELECT id, name, grade, personal_record, events FROM athletes ORDER BY name
`

func (q *Queries) GetAllAthletes(ctx context.Context) ([]Athlete, error) {
	rows, err := q.db.QueryContext(ctx, getAllAthletes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Athlete
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Grade,
			&i.PersonalRecord,
			&i.Events,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMeets = `-- name: GetAllMeets :many
SELECT id, name, date, location, description FROM meets ORDER BY date
`

func (q *Queries) GetAllMeets(ctx context.Context) ([]Meet, error) {
	rows, err := q.db.QueryContext(ctx, getAllMeets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meet
	for rows.Next() {
		var i Meet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Location,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAthleteByID = `-- name: GetAthleteByID :one
SELECT id, name, grade, personal_record, events FROM athletes WHERE id = ?
`

func (q *Queries) GetAthleteByID(ctx context.Context, id int32) (Athlete, error) {
	row := q.db.QueryRowContext(ctx, getAthleteByID, id)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Grade,
		&i.PersonalRecord,
		&i.Events,
	)
	return i, err
}

const getMeetByID = `-- name: GetMeetByID :one
SELECT id, name, date, location, description FROM meets WHERE id = ?
`

func (q *Queries) GetMeetByID(ctx context.Context, id int32) (Meet, error) {
	row := q.db.QueryRowContext(ctx, getMeetByID, id)
	var i Meet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.Location,
		&i.Description,
	)
	return i, err
}

const getMeetResults = `-- name: GetMeetResults :many
SELECT r.id, r.athlete_id, r.meet_id, r.event, r.time, r.place, a.name AS athlete_name, a.grade AS athlete_grade
FROM results r
JOIN athletes a ON a.id = r.athlete_id
WHERE r.meet_id = ?
ORDER BY r.place
`

type GetMeetResultsRow struct {
	ID           int32
	AthleteID    int32
	MeetID       int32
	Event        string
	Time         string
	Place        int32
	AthleteName  string
	AthleteGrade int32
}

func (q *Queries) GetMeetResults(ctx context.Context, meetID int32) ([]GetMeetResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMeetResults, meetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMeetResultsRow
	for rows.Next() {
		var i GetMeetResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.MeetID,
			&i.Event,
			&i.Time,
			&i.Place,
			&i.AthleteName,
			&i.AthleteGrade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingMeets = `-- name: GetUpcomingMeets :many
SELECT id, name, date, location, description FROM meets WHERE date >= CURDATE() ORDER BY date
`

func (q *Queries) GetUpcomingMeets(ctx context.Context) ([]Meet, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingMeets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meet
	for rows.Next() {
		var i Meet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Location,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAthlete = `-- name: UpdateAthlete :exec
UPDATE athletes SET name = ?, grade = ?, personal_record = ?, events = ? WHERE id = ?
`

type UpdateAthleteParams struct {
	Name           string
	Grade          int32
	PersonalRecord string
	Events         string
	ID             int32
}

func (q *Queries) UpdateAthlete(ctx context.Context, arg UpdateAthleteParams) error {
	_, err := q.db.ExecContext(ctx, updateAthlete,
		arg.Name,
		arg.Grade,
		arg.PersonalRecord,
		arg.Events,
		arg.ID,
	)
	return err
}

const updateMeet = `-- name: UpdateMeet :exec
UPDATE meets SET name = ?, date = ?, location = ?, description = ? WHERE id = ?
`

type UpdateMeetParams struct {
	Name        string
	Date        time.Time
	Location    string
	Description string
	ID          int32
}

func (q *Queries) UpdateMeet(ctx context.Context, arg UpdateMeetParams) error {
	_, err := q.db.ExecContext(ctx, updateMeet,
		arg.Name,
		arg.Date,
		arg.Location,
		arg.Description,
		arg.ID,
	)
	return err
}

const updateResult = `-- name: UpdateResult :exec
UPDATE results SET athlete_id = ?, meet_id = ?, event = ?, time = ?, place = ? WHERE id = ?
`

type UpdateResultParams struct {
	AthleteID int32
	MeetID    int32
	Event     string
	Time      string
	Place     int32
	ID        int32
}

func (q *Queries) UpdateResult(ctx context.Context, arg UpdateResultParams) error {
	_, err := q.db.ExecContext(ctx, updateResult,
		arg.AthleteID,
		arg.MeetID,
		arg.Event,
		arg.Time,
		arg.Place,
		arg.ID,
	)
	return err
}
